on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build
        run: dotnet build --no-restore --configuration Release --nologo
      - name: Archive
        run: Compress-Archive -Path Artisan/bin/Release/* -DestinationPath Artisan.zip
      - uses: actions/upload-artifact@v2.2.1
        with:
          path: |
            ./Artisan/bin/Release/*
